name: Deploy CyberCampus CTF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          cd ~/cybercampus-ctf

          echo "📥 Pull des dernières modifications..."
          git pull origin main

          echo "🛑 Arrêt des conteneurs..."
          docker-compose down

          echo "🚀 Rebuild et relance..."
          docker-compose up --build -d

          echo "✅ Déploiement terminé !"
